name: clonephone
description: "this is a clone of phone call to help me grab the concept of statemanagement using riverpond ,routes,api using json,shared preferences,search card,floating button,slide delete,center or fill in diffent screens"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  go_router: ^14.6.0
  shared_preferences: ^2.3.3
  flutter_adaptive_scaffold: ^0.3.1
  flutter_riverpod: ^2.6.1
  freezed_annotation: ^2.4.4
  path_provider: ^2.1.5
  path: ^1.9.0
  permission_handler: ^11.3.1
  contacts_service: ^0.6.3
  call_log: ^4.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0
  freezed: ^2.5.2
  build_runner: ^2.4.11

flutter:


  uses-material-design: true

